<div class="content" x-data="{ tab: 'info', activeLanguage: 'it', quickIngredient: '' }"><div class="main-content">
 <div class="md:flex block items-center justify-between mb-6 page-header-breadcrumb"><div><h5 class="page-title text-[1.3125rem] font-medium mb-0">Prodotti</h5><p class="text-textmuted text-sm mt-1">Catalogo centrale per menu, asporto e comande.</p></div><button wire:click="create" class="ti-btn ti-btn-primary-full"><i class="las la-plus"></i> Nuovo prodotto</button></div>
 @if(session('success'))<div class="alert alert-success mb-4">{{ session('success') }}</div>@endif
 <div class="grid md:grid-cols-4 gap-4 mb-5"><div class="box !mb-0"><div class="box-body"><span class="text-xs text-textmuted">Prodotti</span><b class="block text-2xl">{{ $products->total() }}</b></div></div><div class="box !mb-0"><div class="box-body"><span class="text-xs text-textmuted">Suggerimenti attivi</span><b class="block text-2xl">{{ $products->getCollection()->sum(fn($p) => $p->recommendations->count()) }}</b></div></div></div>
 <div class="box"><div class="box-body"><div class="flex gap-3 mb-5"><input wire:model.live.debounce.300ms="search" class="form-control flex-1" placeholder="Cerca prodotto..."><select wire:model.live="departmentFilter" class="form-control !w-auto"><option value="">Tutti i reparti</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div class="table-responsive"><table class="table table-bordered min-w-full"><thead><tr><th>Prodotto</th><th>Reparto</th><th>Ingredienti</th><th>Suggerimenti</th><th>Prezzo</th><th>Azioni</th></tr></thead><tbody>
 @forelse($products as $product)<tr><td><b>{{ $product->translatedName('it') }}</b><div class="text-xs text-textmuted">{{ $product->translatedName('en') }}</div></td><td>{{ $product->department?->name ?? '—' }}</td><td>{{ $product->ingredients_count }}</td><td>@if($product->recommendations->where('type','upsell')->count())<span class="badge bg-warning/10 !text-warning">↑ Upsell</span>@endif @if($product->recommendations->where('type','cross_sell')->count())<span class="badge bg-primary/10 !text-primary">+ Cross-sell</span>@endif</td><td><b>{{ Number::currency($product->price,'EUR','it') }}</b></td><td><div class="flex gap-2"><button wire:click="edit('{{ $product->id }}')" class="ti-btn ti-btn-icon bg-warning text-white"><i class="las la-pen"></i></button><button wire:click="delete('{{ $product->id }}')" wire:confirm="Eliminare il prodotto?" class="ti-btn ti-btn-icon bg-danger text-white"><i class="las la-trash"></i></button></div></td></tr>@empty<tr><td colspan="6" class="text-center text-textmuted py-10">Nessun prodotto nel catalogo.</td></tr>@endforelse
 </tbody></table></div><div class="mt-4">{{ $products->links() }}</div></div></div>
 @if($showForm)<div class="fixed inset-0 z-[1000] flex items-start justify-center overflow-y-auto bg-black/50 px-3 pb-3 pt-20 sm:px-4 sm:pb-4" wire:click.self="$set('showForm', false)"><div class="box flex max-h-[calc(100dvh-6rem)] w-full max-w-5xl flex-col overflow-hidden !mb-0"><div class="box-header z-10 flex shrink-0 items-center justify-between gap-4 border-b border-defaultborder bg-white dark:bg-bodybg"><h3 class="box-title !mb-0">{{ $editingId ? 'Modifica prodotto' : 'Nuovo prodotto' }}</h3><button type="button" wire:click="$set('showForm', false)" class="ti-btn ti-btn-icon ti-btn-light ms-auto shrink-0 !mb-0" aria-label="Chiudi"><i class="las la-times text-xl"></i></button></div>
  <div class="flex shrink-0 gap-6 overflow-x-auto border-b px-5"><button type="button" @click="tab='info'" :class="tab==='info'?'text-primary border-primary':'text-textmuted border-transparent'" class="whitespace-nowrap border-b-2 py-3">Informazioni</button><button type="button" @click="tab='recipe'" :class="tab==='recipe'?'text-primary border-primary':'text-textmuted border-transparent'" class="whitespace-nowrap border-b-2 py-3">Ingredienti e allergeni</button><button type="button" @click="tab='selling'" :class="tab==='selling'?'text-primary border-primary':'text-textmuted border-transparent'" class="whitespace-nowrap border-b-2 py-3">Upsell e cross-sell</button></div>
  <form wire:submit="save" class="flex min-h-0 flex-1 flex-col"><div class="box-body min-h-0 flex-1 overflow-y-auto overscroll-contain"><div x-show="tab==='info'" class="space-y-5">
   <section>
    <h4 class="mb-3 font-semibold">Nome e descrizione</h4>
    <div class="-mx-1 overflow-x-auto px-1"><nav role="tablist" aria-label="Lingue prodotto" class="--prevent-on-load-init flex min-w-max gap-2 rounded-xl border border-defaultborder bg-defaultbackground p-1">
     @foreach (['it' => ['flag' => '🇮🇹', 'label' => 'Italiano'], 'en' => ['flag' => '🇬🇧', 'label' => 'English'], 'de' => ['flag' => '🇩🇪', 'label' => 'Deutsch']] as $language => $meta)
      <button type="button" role="tab" :aria-selected="activeLanguage === '{{ $language }}'" @click="activeLanguage = '{{ $language }}'" class="ti-btn !mb-0 inline-flex items-center justify-center gap-2 rounded-lg !px-4 !py-2 text-sm font-semibold transition" :class="activeLanguage === '{{ $language }}' ? 'ti-btn-primary-full shadow-sm' : 'ti-btn-light text-defaulttextcolor'"><span>{{ $meta['flag'] }}</span><span>{{ $meta['label'] }}</span></button>
     @endforeach
    </nav></div>
    <div class="mt-3 rounded border border-defaultborder bg-defaultbackground p-4">
     <section x-cloak x-show="activeLanguage === 'it'" x-transition.opacity role="tabpanel" class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label for="product-name-it" class="mb-2 block text-sm font-medium">Nome</label><input id="product-name-it" wire:model="nameIt" class="form-control">@error('nameIt')<span class="mt-1 block text-xs text-danger">{{ $message }}</span>@enderror</div><div><label for="product-description-it" class="mb-2 block text-sm font-medium">Descrizione</label><textarea id="product-description-it" wire:model="descriptionIt" rows="2" class="form-control"></textarea></div></section>
     <section x-cloak x-show="activeLanguage === 'en'" x-transition.opacity role="tabpanel" class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label for="product-name-en" class="mb-2 block text-sm font-medium">Nome</label><input id="product-name-en" wire:model="nameEn" class="form-control"></div><div><label for="product-description-en" class="mb-2 block text-sm font-medium">Descrizione</label><textarea id="product-description-en" wire:model="descriptionEn" rows="2" class="form-control"></textarea></div></section>
     <section x-cloak x-show="activeLanguage === 'de'" x-transition.opacity role="tabpanel" class="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label for="product-name-de" class="mb-2 block text-sm font-medium">Nome</label><input id="product-name-de" wire:model="nameDe" class="form-control"></div><div><label for="product-description-de" class="mb-2 block text-sm font-medium">Descrizione</label><textarea id="product-description-de" wire:model="descriptionDe" rows="2" class="form-control"></textarea></div></section>
    </div>
   </section>
   <section class="grid grid-cols-1 gap-4 border-t border-defaultborder pt-4 md:grid-cols-[12rem_minmax(0,1fr)]"><div>@if($image)<img src="{{ $image->temporaryUrl() }}" alt="Anteprima prodotto" class="h-32 w-full rounded-lg object-cover">@elseif($existingImagePath)<img src="{{ Storage::url($existingImagePath) }}" alt="Immagine prodotto" class="h-32 w-full rounded-lg object-cover">@else<div class="grid h-32 place-items-center rounded-lg border border-dashed border-defaultborder bg-light text-center text-xs text-textmuted"><i class="las la-image mb-1 block text-3xl"></i>Nessuna immagine</div>@endif</div><div><label for="product-image" class="mb-2 block text-sm font-medium">Immagine prodotto</label><input id="product-image" wire:model="image" type="file" accept="image/jpeg,image/png,image/webp" class="form-control"><p class="mt-2 text-xs text-textmuted">JPG, PNG o WebP, massimo 5 MB. Consigliato formato orizzontale 4:3.</p>@error('image')<span class="mt-1 block text-xs text-danger">{{ $message }}</span>@enderror<div wire:loading wire:target="image" class="mt-2 text-xs text-primary">Caricamento anteprima…</div>@if($existingImagePath || $image)<button type="button" wire:click="removeImage" class="ti-btn ti-btn-light mt-3 !mb-0 !text-danger">Rimuovi immagine</button>@endif</div></section>
   <section class="grid grid-cols-1 gap-4 border-t border-defaultborder pt-4 md:grid-cols-3"><div><label for="product-price" class="mb-2 block text-sm font-medium">Prezzo</label><div class="input-group"><span class="input-group-text">€</span><input id="product-price" wire:model="price" type="number" min="0" step=".01" class="form-control"></div></div><div><label for="product-department" class="mb-2 block text-sm font-medium">Reparto</label><select id="product-department" wire:model="departmentId" class="form-control"><option value="">Nessuno</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div><label for="product-vat" class="mb-2 block text-sm font-medium">IVA (%)</label><input id="product-vat" wire:model="vat" type="number" min="0" max="100" class="form-control"></div></section>
   <section class="flex flex-col gap-3 border-t border-defaultborder pt-4 md:flex-row md:flex-nowrap"><label class="flex min-w-0 cursor-pointer items-center gap-3 rounded border border-defaultborder p-3 md:w-1/2"><input wire:model="isActive" type="checkbox" class="ti-switch shrink-0"><span class="font-medium">Disponibile</span></label><label class="flex min-w-0 cursor-pointer items-center gap-3 rounded border border-defaultborder p-3 md:w-1/2"><input wire:model="disallowTakeaway" type="checkbox" class="ti-switch shrink-0"><span class="font-medium">Escludi dall'asporto</span></label></section>
  </div>
   <div x-show="tab==='recipe'" x-cloak><div class="mb-5"><label class="form-label">Crea ingrediente senza lasciare il prodotto</label><div class="flex mt-2 gap-2"><input x-model="quickIngredient" class="form-control" placeholder="Nome ingrediente"><button type="button" class="ti-btn ti-btn-light" @click="$wire.quickIngredient(quickIngredient); quickIngredient=''">+ Crea e abbina</button></div></div><div class="grid md:grid-cols-2 gap-3">@foreach($ingredients as $ingredient)<label class="border rounded p-3 flex items-center gap-3"><input type="checkbox" @checked(array_key_exists($ingredient->id,$ingredientQuantities)) x-on:change="$event.target.checked ? $wire.set('ingredientQuantities.{{ $ingredient->id }}', 1) : $wire.set('ingredientQuantities.{{ $ingredient->id }}', null)"><span class="flex-1">{{ $ingredient->translatedName('it') }}</span><input wire:model="ingredientQuantities.{{ $ingredient->id }}" type="number" step=".001" class="form-control !w-24" placeholder="Qtà"><small>{{ $ingredient->unit }}</small></label>@endforeach</div><h6 class="mt-6 mb-3 font-semibold">Allergeni</h6><div class="grid md:grid-cols-3 gap-2">@foreach(['glutine','crostacei','uova','pesce','arachidi','soia','latte','frutta a guscio','sedano','senape','sesamo','solfiti','lupini','molluschi'] as $allergen)<label class="border rounded p-2"><input wire:model="allergens" value="{{ $allergen }}" type="checkbox"> <span class="capitalize">{{ $allergen }}</span></label>@endforeach</div></div>
   <div x-show="tab==='selling'" x-cloak class="grid md:grid-cols-2 gap-5"><div class="border border-warning/30 bg-warning/5 rounded p-4"><h5 class="font-semibold">↑ Upsell</h5><p class="text-xs text-textmuted mb-3">Una versione o alternativa di maggior valore.</p><select wire:model="upsellIds" multiple class="form-control min-h-40">@foreach($recommendableProducts as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->translatedName('it') }} · {{ Number::currency($candidate->price,'EUR','it') }}</option>@endforeach</select></div><div class="border border-primary/30 bg-primary/5 rounded p-4"><h5 class="font-semibold">+ Cross-sell</h5><p class="text-xs text-textmuted mb-3">Prodotti complementari da proporre dopo l'aggiunta.</p><select wire:model="crossSellIds" multiple class="form-control min-h-40">@foreach($recommendableProducts as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->translatedName('it') }} · {{ Number::currency($candidate->price,'EUR','it') }}</option>@endforeach</select></div></div>
  </div><div class="box-footer z-10 flex shrink-0 justify-end gap-2 border-t border-defaultborder bg-white dark:bg-bodybg"><button type="button" wire:click="$set('showForm', false)" class="ti-btn ti-btn-light !mb-0">Annulla</button><button class="ti-btn ti-btn-primary-full !mb-0">Salva prodotto</button></div></form></div></div>@endif
 </div></div>
