<div style="--menu-primary: {{ data_get($menu->theme,'primary','#0f766e') }}" class="min-h-screen pb-24">
 <header class="relative h-64 bg-gradient-to-br from-[#173e38] to-[var(--menu-primary)] text-white"><div class="absolute inset-0 bg-black/10"></div><div class="relative max-w-3xl mx-auto h-full px-5 flex flex-col justify-end pb-8"><div class="mb-auto flex h-16 w-full items-center justify-between gap-3 pt-1" style="--tenant-form-header-height: 4rem">
  <div class="flex min-w-0 items-center gap-3 overflow-hidden">@if($branding['logo_url'])<img src="{{ $branding['logo_url'] }}" alt="{{ $branding['name'] }}" class="tenant-public-form-logo" style="display:block; width:auto !important; height:auto !important; max-width:11rem !important; max-height:3rem !important; object-fit:contain">@endif</div>
  @if(count($languages) > 1)<div><label for="menu-language" class="sr-only">{{ __('public_bookings.language') }}</label><select id="menu-language" onchange="window.location.href = this.value" class="appearance-none rounded-lg border border-gray-300 bg-white px-5 py-2 pr-8 text-sm text-gray-800 focus:border-gray-500 focus:outline-none">@foreach($languages as $code => $meta)<option value="{{ route('menu.public',['language'=>$code,'menu'=>$menu]) }}" @selected($language === $code)>{{ $meta['flag'] }} {{ strtoupper($code) }}</option>@endforeach</select></div>@endif
 </div>
 {{-- <p class="uppercase tracking-[.25em] text-xs opacity-75 mb-2">Menu digitale</p> --}}
 <h1 class="font-serif text-4xl font-semibold text-white">{{ $menu->translatedName($language) }}</h1><p class="mt-2 text-white/80">{{ $menu->translatedDescription($language) }}</p></div></header>
 <nav class="sticky top-0 z-20 bg-[#f8f6f1]/95 backdrop-blur border-b border-[#dedbd1]"><div class="max-w-3xl mx-auto px-4 py-3 flex gap-2 overflow-x-auto">@foreach($menu->categories as $category)<a href="#category-{{ $category->id }}" class="whitespace-nowrap rounded-full border border-[#d8d2c5] px-4 py-2 text-sm hover:bg-[var(--menu-primary)] hover:text-white">{{ $category->translatedName($language) }}</a>@endforeach</div></nav>
 <main class="max-w-3xl mx-auto px-5">@foreach($menu->categories as $category)<section id="category-{{ $category->id }}" class="pt-10 scroll-mt-16"><h2 class="font-serif text-3xl mb-1">{{ $category->translatedName($language) }}</h2>@if(data_get($category->description,$language))<p class="text-[#77746d] mb-5">{{ data_get($category->description,$language) }}</p>@endif<div class="divide-y divide-[#dedbd1]">
 @foreach($category->products as $product)<article class="py-5"><div class="flex gap-5"><div class="flex-1"><div class="flex items-start justify-between gap-4"><h3 class="font-serif text-xl font-semibold">{{ $product->translatedName($language) }}</h3><b class="whitespace-nowrap">{{ Number::currency($product->pivot->menu_price ?? $product->price,'EUR','it') }}</b></div><p class="text-sm leading-6 text-[#77746d] mt-2">{{ $product->translatedDescription($language) }}</p>@if($product->allergens)<p class="text-xs text-[#8c6646] mt-2">Allergeni: {{ implode(', ',$product->allergens) }}</p>@endif</div>@if($product->image_path)<img src="{{ Storage::url($product->image_path) }}" alt="" class="w-24 h-24 rounded-xl object-cover">@endif</div>
 @php($upsells=$product->recommendations->where('type','upsell')) @if($upsells->isNotEmpty())<div class="mt-4 rounded-xl bg-[#fff4d9] border border-[#ead5a0] p-4"><b class="text-sm text-[#765b18]">✨ {{ $language==='en'?'Make it special':'Rendilo speciale' }}</b><div class="flex flex-wrap gap-2 mt-2">@foreach($upsells as $recommendation)<span class="bg-white rounded-lg px-3 py-2 text-sm">{{ $recommendation->recommendedProduct->translatedName($language) }} · {{ Number::currency($recommendation->recommendedProduct->price,'EUR','it') }}</span>@endforeach</div></div>@endif
 @php($crossSells=$product->recommendations->where('type','cross_sell')) @if($crossSells->isNotEmpty())<div class="mt-3"><span class="text-xs uppercase tracking-wider text-[#77746d]">{{ $language==='en'?'Perfect with':'Perfetto con' }}</span><div class="flex gap-2 overflow-x-auto mt-2">@foreach($crossSells as $recommendation)<span class="whitespace-nowrap border border-[#d8d2c5] rounded-full px-3 py-2 text-sm">+ {{ $recommendation->recommendedProduct->translatedName($language) }}</span>@endforeach</div></div>@endif
 </article>@endforeach</div></section>@endforeach
 @if($menu->service_charge>0)<div class="mt-10 p-4 border border-[#d8d2c5] rounded-xl text-sm">Servizio: {{ Number::currency($menu->service_charge,'EUR','it') }}</div>@endif</main>
 <footer class="text-center text-xs text-[#89867e] py-12">Powered by RistoPilot</footer>
</div>
