<?php

$it = require __DIR__.'/../it/bookings.php';

return array_replace_recursive($it, [
    'title' => 'Reservierungen', 'back' => 'Zurück', 'next' => 'Weiter', 'today' => 'Heute', 'refresh' => 'Reservierungen aktualisieren', 'search' => 'Reservierungen suchen', 'new' => 'Neue Reservierung', 'edit' => 'Reservierung bearbeiten', 'detail' => 'Reservierungsdetails', 'detail_heading' => 'RESERVIERUNGSDETAILS', 'waitlist' => 'Warteliste', 'walk_in' => 'Neuer Walk-in', 'lunch' => 'Mittagessen', 'dinner' => 'Abendessen', 'all_day' => 'Ganzer Tag', 'room' => 'Raum', 'timeslots' => 'Reservierungen nach Zeitfenster anzeigen', 'slot' => 'Zeitfenster', 'booked' => 'Gebucht', 'closed' => 'Restaurant an diesem Datum geschlossen.', 'arriving' => 'Ankommend', 'serving' => 'Bedient', 'customer_booking' => 'Kunde / Reservierung', 'tables_stay' => 'Tische / Aufenthalt', 'empty' => 'Keine Reservierungen für die aktuelle Auswahl.', 'close' => 'Schließen', 'confirm' => 'Bestätigen', 'operation_confirm' => 'Vorgang bestätigen', 'status_confirm' => 'Änderung des Reservierungsstatus bestätigen?', 'booking_notes' => 'Reservierungsnotizen',
    'form' => ['hint' => 'Mindestens 4 Zeichen in ein Kundenfeld eingeben, um einen bestehenden Kunden zu suchen.', 'phone' => 'Vorwahl und Telefon', 'prefix' => 'Vorwahl', 'email' => 'E-Mail', 'firstname' => 'Vorname', 'lastname' => 'Nachname', 'date' => 'Datum', 'time' => 'Uhrzeit', 'select_time' => 'Uhrzeit auswählen', 'people' => 'Personenzahl', 'customer_language' => 'Kundensprache', 'status' => 'Status', 'notes' => 'Notizen', 'send_proposal' => 'Änderungsvorschlag an den Kunden senden', 'send_proposal_help' => 'Wenn diese Option aktiviert ist, wird beim Speichern ein Vorschlag an den Kunden gesendet.', 'restaurant_note' => 'Notizen des Restaurants', 'assign_tables' => 'Tische zuweisen', 'save' => 'Reservierung speichern', 'delete' => 'Löschen', 'delete_confirm' => 'Reservierung löschen?'],
    'statuses' => ['pending' => 'Eingetragen', 'booking_sent' => 'Gesendet', 'accepted' => 'Angenommen', 'denied' => 'Abgelehnt', 'canceled' => 'Storniert', 'no-show' => 'No show', 'seated' => 'Platziert', 'waiting' => 'Wartend', 'finalized' => 'Abgeschlossen'],
    'tables' => ['title' => 'Zugewiesene Tische verwalten', 'description' => 'Einen oder mehrere Tische für diese Reservierung auswählen.', 'search' => 'Tisch oder Raum suchen', 'selected' => 'Ausgewählte Tische', 'available' => 'Verfügbare Tische', 'empty' => 'Keine Tische mit diesen Kriterien verfügbar.', 'confirm' => 'Auswahl bestätigen', 'none' => 'Keine Tische ausgewählt.', 'one' => 'Tisch ausgewählt', 'many' => 'Tische ausgewählt', 'roomless' => 'Ohne Raum', 'select_first' => 'Zuerst eine Uhrzeit auswählen.'],
    'show' => ['status' => 'Status', 'datetime' => 'Datum und Uhrzeit', 'at' => 'um', 'people' => 'Personen', 'tables' => 'Tische', 'unassigned' => 'Nicht zugewiesen', 'customer' => 'Kunde', 'language' => 'Sprache', 'customer_notes' => 'Kundennotizen', 'origin' => 'Quelle', 'created_at' => 'Erstellt am', 'history' => 'Änderungsverlauf der Reservierung', 'date' => 'Datum', 'event' => 'Ereignis', 'author' => 'Autor', 'details' => 'Details', 'no_history' => 'Keine Änderungen erfasst.', 'events' => ['created' => 'Erstellt', 'updated' => 'Geändert', 'status_changed' => 'Status geändert', 'booking_canceled' => 'Storniert', 'tables_changed' => 'Tische geändert', 'deleted' => 'Gelöscht']],
    'waitlist_page' => ['title' => 'Warteliste', 'refresh' => 'Liste aktualisieren', 'manage' => 'Wartelistenverwaltung', 'search' => 'Kunde suchen', 'search_placeholder' => 'Vorname, Nachname, E-Mail oder Telefon', 'add_customer' => 'Kunde hinzufügen', 'new_customer' => 'Neuer wartender Kunde', 'existing' => 'Bestehender Kunde ausgewählt', 'add' => 'Hinzufügen', 'actions' => 'Aktionen', 'customer' => 'Kunde', 'people' => 'Personen', 'added_at' => 'Hinzugefügt um', 'wait' => 'Wartezeit', 'status' => 'Status', 'notified' => 'Benachrichtigt', 'waiting' => 'Wartend', 'empty' => 'Heute steht niemand auf der Warteliste.', 'notify' => 'Kunden benachrichtigen', 'seat' => 'Platzieren', 'remove' => 'Entfernen'],
    'walkin_page' => ['create' => 'NEUEN WALK-IN ERSTELLEN', 'description' => 'Zeitfenster belegen, ohne personenbezogene Kundendaten zu speichern.', 'table_assignment' => 'Tischzuweisung', 'select_tables' => 'Tische auswählen', 'save' => 'Walk-in speichern', 'stats' => 'Reservierungen nach Zeitfenster (:date)'],
    'messages' => ['select_datetime' => 'Datum und Uhrzeit vor der Tischzuweisung auswählen.', 'select_time' => 'Vor der Tischauswahl eine Uhrzeit auswählen.', 'saved' => 'Reservierung erfolgreich gespeichert.', 'deleted' => 'Reservierung gelöscht.', 'tables_saved' => 'Tische erfolgreich zugewiesen.', 'walkin_saved' => 'Walk-in erfolgreich hinzugefügt.', 'contact_required' => 'Mindestens eine E-Mail-Adresse oder Telefonnummer eingeben.', 'customer_phone_taken' => 'Diese Telefonnummer ist bereits einem Kunden zugeordnet. Wählen Sie den bestehenden Kunden aus den Vorschlägen aus.', 'customer_email_taken' => 'Diese E-Mail-Adresse ist bereits einem Kunden zugeordnet. Wählen Sie den bestehenden Kunden aus den Vorschlägen aus.', 'waitlist_added' => 'Kunde zur Warteliste hinzugefügt.', 'waitlist_seated' => 'Kunde platziert und zu den heutigen Reservierungen hinzugefügt.', 'waitlist_removed' => 'Kunde von der Warteliste entfernt.'],
    'actions' => ['accept' => 'Annehmen', 'deny' => 'Ablehnen', 'accept_confirm' => 'Diese Reservierung annehmen?', 'deny_confirm' => 'Diese Reservierung ablehnen?'],
    'proposal_requires_changes' => 'Ändern Sie Datum, Uhrzeit oder Personenzahl, um einen Vorschlag zu senden.',
]);
