<?php

return [
    'title'=>'Kunden','home'=>'Startseite','back'=>'Zurück','save'=>'Speichern','cancel'=>'Abbrechen','yes'=>'JA','no'=>'NEIN','language'=>'Sprache','info'=>'Info',
    'actions'=>['create'=>'Kunde erstellen','import'=>'Kunden aus CSV importieren','refresh'=>'Aktualisieren','view'=>'Anzeigen','edit'=>'Bearbeiten','delete'=>'Löschen'],
    'index'=>['search'=>'Kunden suchen','advanced_filters'=>'Erweiterte Filter','reset_filters'=>'Filter zurücksetzen','send_marketing'=>'An Marketing senden','customer'=>'Kunde','last_visit'=>'Letzter Besuch','area'=>'Gebiet','empty'=>'Keine Kunden gefunden.'],
    'filters'=>['all_f'=>'-- Alle --','all_m'=>'-- Alle --','none'=>'-- Kein Filter --','province'=>'Provinz','municipality'=>'Gemeinde','booking_status'=>'Reservierungsstatus','no_show'=>'No Show >=','example'=>'Z. B. 1, 2, 3...','visit_from'=>'Letzter Besuch (von)','visit_to'=>'Letzter Besuch (bis)','not_visited_since'=>'Nicht besucht seit','visited_within'=>'Besucht innerhalb','birth_month'=>'Geburtsmonat','birth_day'=>'Geburtstag','month'=>':count Monat|:count Monate','over_year'=>'Über 1 Jahr'],
    'months'=>['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
    'statuses'=>['pending'=>'Eingetragen','accepted'=>'Angenommen','denied'=>'Abgelehnt','canceled'=>'Storniert','no-show'=>'No show','seated'=>'Platziert','waiting'=>'Wartend','finalized'=>'Abgeschlossen','deleted'=>'Gelöscht'],
    'form'=>['create'=>'KUNDE ERSTELLEN','edit'=>'KUNDE BEARBEITEN','firstname'=>'Vorname','lastname'=>'Nachname','email'=>'E-Mail','phone'=>'Telefon','telegram'=>'Telegram-ID','birthdate'=>'Geburtsdatum','region'=>'Region','province'=>'Provinz','municipality'=>'Gemeinde','select_region'=>'-- Region auswählen --','select_province'=>'-- Provinz auswählen --','select_municipality'=>'-- Gemeinde auswählen --','notes'=>'Interne Notizen (für den Kunden nicht sichtbar)','notes_placeholder'=>'Notizen zu diesem Kunden hier eingeben.','marketing'=>'Marketing-Einwilligung','blacklisted'=>'Auf der Sperrliste'],
    'show'=>['card'=>'KUNDE :name','create_booking'=>'Reservierung erstellen','source'=>'Quelle'],
    'delete'=>['title'=>'KUNDE LÖSCHEN','confirm'=>'Möchtest du :name wirklich löschen?','button'=>'Ja, löschen'],
    'import'=>['title'=>'KUNDEN AUS CSV IMPORTIEREN','file'=>'CSV-Datei','sync'=>'Synchronisieren','loading'=>'Wird hochgeladen...','documentation'=>'DOKUMENTATION','heading'=>'Kunden über CSV importieren','intro'=>'Diese Seite bereitet den Massenimport von Kunden vor. Die Importfunktion wird später implementiert.','recommended'=>'Empfohlene Felder','field'=>'Feld','description'=>'Beschreibung','example'=>'Beispiel','firstname'=>'Vorname des Kunden.','lastname'=>'Nachname des Kunden.','phone'=>'Telefonnummer möglichst im internationalen Format.','email'=>'E-Mail-Adresse des Kunden.','birthdate'=>'Geburtsdatum im ISO-Format.'],
    'history'=>['title'=>'Reservierungshistorie des Kunden (:count)','finalized'=>'Abgeschlossen','canceled'=>'Storniert/gelöscht','denied'=>'Abgelehnt','no_show'=>'No show','date'=>'Datum','time'=>'Uhrzeit','pax'=>'Personen','status'=>'Status','notes'=>'Notizen','empty'=>'Keine Reservierungen für diesen Kunden.'],
    'messages'=>['created'=>'Kunde erfolgreich erstellt.','updated'=>'Kunde erfolgreich aktualisiert.','deleted'=>'Kunde erfolgreich gelöscht.','marketing_pending'=>'Die Marketingfunktion wird später implementiert.','import_pending'=>'Der CSV-Kundenimport ist vorbereitet: Die Synchronisierung wird später implementiert.'],
];
