<?php
$it = require __DIR__.'/../it/reservation_settings.php';
return array_replace_recursive($it, [
 'common'=>['save'=>'Speichern','cancel'=>'Abbrechen','add'=>'Hinzufügen','remove'=>'Entfernen','yes'=>'Ja','no'=>'Nein','from'=>'Von','to'=>'Bis','actions'=>'Aktionen','name'=>'Name','weekdays'=>'Wochentage'],
 'index'=>['title'=>'Einstellungen','reservations'=>'Reservierungen','reservations_help'=>'Im Mandantenprofil gespeicherte Betriebseinstellungen.','hours'=>'Öffnungszeiten','pax'=>'Maximale Gäste pro Zeitfenster','sitting'=>'Maximale Verweildauer am Tisch (in Minuten)','notifications'=>'Benachrichtigungskanäle','operations'=>'Betrieb','operations_help'=>'Abteilungen für Personal, Produktion und Bestelldruck.','departments'=>'Abteilungen','rooms'=>'Räume','automations'=>'Automatisierungen','automations_help'=>'Automatische Regeln für Reservierungen.','reminder_question'=>'Wie viele Stunden vor der Reservierung soll der Kunde erinnert werden?'],
 'reminder'=>['title'=>'Reservierungserinnerung','updated'=>'Stunden für die Reservierungserinnerung erfolgreich aktualisiert.'],
 'sitting'=>['title'=>'Maximale Verweildauer am Tisch','label'=>'Maximale Verweildauer am Tisch (in Minuten)','updated'=>'Maximale Verweildauer erfolgreich aktualisiert.'],
 'notifications'=>['title'=>'Benachrichtigungskanäle','updated'=>'Benachrichtigungskanäle erfolgreich aktualisiert.'],
 'opening'=>['title'=>'Öffnungszeiten','help'=>'Standardzeiten und besondere Schließungen nach Datumsbereich konfigurieren.','slot_size'=>'Zeitfensterdauer','slot_help'=>'Bestimmt die Dauer der Zeitfenster für Mittag- und Abendessen.','minutes'=>':count Minuten','availability'=>'Verfügbarkeit und Zeiträume verwalten.','meal_open'=>':meal geöffnet','start'=>'Beginn :meal','end'=>'Ende :meal','special'=>'Besondere Schließungen / ausgebucht','special_help'=>'Datumsbereiche konfigurieren, in denen Mittag- oder Abendessen nicht buchbar sind.','lunch_closed'=>'Mittagessen geschlossen','dinner_closed'=>'Abendessen geschlossen','empty'=>'Keine besonderen Schließungen konfiguriert.','save'=>'Öffnungszeiten speichern','service_error'=>'Mindestens einen zu schließenden Service auswählen.','updated'=>'Öffnungszeiten erfolgreich aktualisiert.'],
 'pax'=>['title'=>'Gäste pro Zeitfenster','help'=>'Standardkapazität und Ausnahmen nach Datumsbereich festlegen.','fallback'=>'Standardgästezahl','fallback_help'=>'Gästezahl, wenn für ein Zeitfenster kein eigener Wert festgelegt ist.','apply'=>'Standardwert auf alle wöchentlichen Zeitfenster anwenden','max'=>'Maximale Gäste pro Zeitfenster.','closed'=>'Service geschlossen oder keine Zeitfenster konfiguriert.','ranges'=>'Konfiguration für bestimmte Datumsbereiche','ranges_help'=>'Ausnahmen oder Zeiträume mit abweichender Kapazität verwalten.','lunch'=>'Gäste Mittagessen','dinner'=>'Gäste Abendessen','standard'=>'Standard','empty'=>'Kein bestimmter Datumsbereich konfiguriert.','save'=>'Gästekapazität speichern','value_error'=>'Mindestens einen Wert für die Gästekapazität eingeben.','updated'=>'Gästekapazität erfolgreich aktualisiert.'],
 'days'=>['lunedi'=>'Montag','martedi'=>'Dienstag','mercoledi'=>'Mittwoch','giovedi'=>'Donnerstag','venerdi'=>'Freitag','sabato'=>'Samstag','domenica'=>'Sonntag'],
 'day_short'=>['lunedi'=>'Mo','martedi'=>'Di','mercoledi'=>'Mi','giovedi'=>'Do','venerdi'=>'Fr','sabato'=>'Sa','domenica'=>'So'],
 'meals'=>['pranzo'=>'Mittagessen','cena'=>'Abendessen'],
]);
