<?php

$it = require __DIR__.'/../it/bookings.php';

return array_replace_recursive($it, [
    'title' => 'Bookings', 'back' => 'Back', 'next' => 'Next', 'today' => 'Today', 'refresh' => 'Refresh bookings', 'search' => 'Search bookings', 'new' => 'New booking', 'edit' => 'Edit booking', 'detail' => 'Booking details', 'detail_heading' => 'BOOKING DETAILS', 'waitlist' => 'Waitlist', 'walk_in' => 'New Walk In', 'lunch' => 'Lunch', 'dinner' => 'Dinner', 'all_day' => 'All day', 'room' => 'Room', 'list' => 'List', 'expand' => 'Expand', 'collapse' => 'Collapse', 'fullscreen' => 'Open fullscreen', 'exit_fullscreen' => 'Exit fullscreen', 'timeslots' => 'Bookings by time slot', 'slot' => 'Time slot', 'booked' => 'Booked', 'closed' => 'Restaurant closed on this date.', 'arriving' => 'Arriving', 'serving' => 'Serving', 'customer_booking' => 'Customer / booking', 'tables_stay' => 'Tables / stay', 'empty' => 'No bookings for the current selection.', 'close' => 'Close', 'confirm' => 'Confirm', 'operation_confirm' => 'Confirm operation', 'status_confirm' => 'Confirm the booking status change?', 'booking_notes' => 'Booking notes',
    'form' => ['hint' => 'Type at least 4 characters in a customer field to find an existing customer.', 'phone' => 'Prefix and phone', 'prefix' => 'Prefix', 'email' => 'Email', 'firstname' => 'First name', 'lastname' => 'Last name', 'date' => 'Date', 'time' => 'Time', 'select_time' => 'Select time', 'people' => 'Number of people', 'customer_language' => 'Customer language', 'status' => 'Status', 'notes' => 'Notes', 'send_proposal' => 'Send a booking change proposal to the customer', 'send_proposal_help' => 'When enabled, saving sends a proposal to the customer instead of performing a simple update.', 'restaurant_note' => 'Restaurant notes', 'assign_tables' => 'Assign tables', 'save' => 'Save booking', 'delete' => 'Delete', 'delete_confirm' => 'Delete this booking?'],
    'statuses' => ['pending' => 'Entered', 'accepted' => 'Accepted', 'denied' => 'Denied', 'canceled' => 'Canceled', 'no-show' => 'No show', 'seated' => 'Seated', 'waiting' => 'Waiting', 'finalized' => 'Completed'],
    'tables' => ['title' => 'Assigned table management', 'description' => 'Select one or more tables for this booking.', 'search' => 'Search table or room', 'selected' => 'Selected tables', 'available' => 'Available tables', 'empty' => 'No tables available with these criteria.', 'confirm' => 'Confirm selection', 'none' => 'No tables selected.', 'one' => 'table selected', 'many' => 'tables selected', 'roomless' => 'No room', 'select_first' => 'Select a time first.'],
    'show' => ['status' => 'Status', 'datetime' => 'Date and time', 'at' => 'at', 'people' => 'People', 'tables' => 'Tables', 'unassigned' => 'Not assigned', 'customer' => 'Customer', 'language' => 'Language', 'customer_notes' => 'Customer notes', 'origin' => 'Source', 'created_at' => 'Created at', 'history' => 'Booking change history', 'date' => 'Date', 'event' => 'Event', 'author' => 'Author', 'details' => 'Details', 'no_history' => 'No changes recorded.', 'events' => ['created' => 'Created', 'updated' => 'Updated', 'status_changed' => 'Status changed', 'booking_canceled' => 'Canceled', 'tables_changed' => 'Tables changed', 'deleted' => 'Deleted']],
    'waitlist_page' => ['title' => 'Waitlist', 'refresh' => 'Refresh list', 'manage' => 'Waitlist management', 'search' => 'Search customer', 'search_placeholder' => 'First name, last name, email or phone', 'add_customer' => 'Add customer', 'new_customer' => 'New Waiting Customer', 'existing' => 'Existing customer selected', 'add' => 'Add', 'actions' => 'Actions', 'customer' => 'Customer', 'people' => 'People', 'added_at' => 'Added at', 'wait' => 'Waiting time', 'status' => 'Status', 'notified' => 'Notified', 'waiting' => 'Waiting', 'empty' => 'No one on today’s waitlist.', 'notify' => 'Notify customer', 'seat' => 'Seat', 'remove' => 'Remove'],
    'walkin_page' => ['create' => 'CREATE NEW WALK IN', 'description' => 'Occupy the slot without recording customer personal data.', 'table_assignment' => 'Table assignment', 'select_tables' => 'Select tables', 'save' => 'Save Walk In', 'stats' => 'Bookings by time slot (:date)'],
    'messages' => ['select_datetime' => 'Select date and time before assigning tables.', 'select_time' => 'Select a time before choosing tables.', 'saved' => 'Booking saved successfully.', 'deleted' => 'Booking deleted.', 'tables_saved' => 'Tables assigned successfully.', 'walkin_saved' => 'Walk In added successfully.', 'contact_required' => 'Enter at least an email address or phone number.', 'customer_phone_taken' => 'This phone number is already associated with a customer. Select the existing customer from the suggestions.', 'customer_email_taken' => 'This email address is already associated with a customer. Select the existing customer from the suggestions.', 'waitlist_added' => 'Customer added to the waitlist.', 'waitlist_seated' => 'Customer seated and added to today’s bookings.', 'waitlist_removed' => 'Customer removed from the waitlist.'],
    'actions' => ['accept' => 'Accept', 'deny' => 'Deny', 'assign' => 'Assign', 'remove_from_table' => 'Remove from table', 'accept_confirm' => 'Accept this booking?', 'deny_confirm' => 'Deny this booking?', 'confirmations' => [
        'accept' => ['title' => 'Confirm acceptance', 'prompt' => 'Do you want to accept the booking for'],
        'deny' => ['title' => 'Confirm rejection', 'prompt' => 'Do you want to reject the booking for'],
        'no_show' => ['title' => 'Confirm No-Show', 'prompt' => 'Do you want to mark as no-show the booking for'],
        'seat' => ['title' => 'Confirm arrival', 'prompt' => 'Do you want to seat'],
        'finalize' => ['title' => 'Confirm completion', 'prompt' => 'Do you want to complete the booking for'],
    ]],
    'proposal_requires_changes' => 'To send a proposal, change the date, time, or number of people.',
]);
