<?php

return [
    'title'=>'Customers','home'=>'Home','back'=>'Back','save'=>'Save','cancel'=>'Cancel','yes'=>'YES','no'=>'NO','language'=>'Language','info'=>'Info',
    'actions'=>['create'=>'Create customer','import'=>'Import customers from CSV','refresh'=>'Refresh','view'=>'View','edit'=>'Edit','delete'=>'Delete'],
    'index'=>['search'=>'Search customers','advanced_filters'=>'Advanced filters','reset_filters'=>'Reset filters','send_marketing'=>'Send to Marketing','customer'=>'Customer','last_visit'=>'Last visit','area'=>'Area','empty'=>'No customers found.'],
    'filters'=>['all_f'=>'-- All --','all_m'=>'-- All --','none'=>'-- No filter --','province'=>'Province','municipality'=>'Municipality','booking_status'=>'Booking status','no_show'=>'No Show >=','example'=>'E.g. 1, 2, 3...','visit_from'=>'Last visit (from)','visit_to'=>'Last visit (to)','not_visited_since'=>'Have not visited for','visited_within'=>'Visited within','birth_month'=>'Birth month','birth_day'=>'Birth day','month'=>':count month|:count months','over_year'=>'Over 1 year'],
    'months'=>['January','February','March','April','May','June','July','August','September','October','November','December'],
    'statuses'=>['pending'=>'Entered','accepted'=>'Accepted','denied'=>'Denied','canceled'=>'Canceled','no-show'=>'No show','seated'=>'Seated','waiting'=>'Waiting','finalized'=>'Completed','deleted'=>'Deleted'],
    'form'=>['create'=>'CREATE CUSTOMER','edit'=>'EDIT CUSTOMER','firstname'=>'First name','lastname'=>'Last name','email'=>'Email','phone'=>'Phone','telegram'=>'Telegram ID','birthdate'=>'Date of birth','region'=>'Region','province'=>'Province','municipality'=>'Municipality','select_region'=>'-- Select Region --','select_province'=>'-- Select Province --','select_municipality'=>'-- Select Municipality --','notes'=>'Internal notes (not visible to the customer)','notes_placeholder'=>'Enter your notes about this customer here.','marketing'=>'Marketing consent','blacklisted'=>'Blacklisted'],
    'show'=>['card'=>'CUSTOMER :name','create_booking'=>'Create booking','source'=>'Source'],
    'delete'=>['title'=>'DELETE CUSTOMER','confirm'=>'Are you sure you want to delete :name?','button'=>'Yes, delete'],
    'import'=>['title'=>'IMPORT CUSTOMERS FROM CSV','file'=>'CSV file','sync'=>'Synchronize','loading'=>'Uploading...','documentation'=>'DOCUMENTATION','heading'=>'Import customers via CSV','intro'=>'This screen prepares bulk customer uploads. The import functionality will be implemented later.','recommended'=>'Recommended fields','field'=>'Field','description'=>'Description','example'=>'Example','firstname'=>'Customer first name.','lastname'=>'Customer last name.','phone'=>'Phone number in international format where possible.','email'=>'Customer email address.','birthdate'=>'Date of birth in ISO format.'],
    'history'=>['title'=>'Customer booking history (:count)','finalized'=>'Completed','canceled'=>'Canceled/deleted','denied'=>'Denied','no_show'=>'No show','date'=>'Date','time'=>'Time','pax'=>'Pax','status'=>'Status','notes'=>'Notes','empty'=>'No bookings for this customer.'],
    'messages'=>['created'=>'Customer created successfully.','updated'=>'Customer updated successfully.','deleted'=>'Customer deleted successfully.','marketing_pending'=>'The marketing feature will be implemented later.','import_pending'=>'CSV customer import is ready: synchronization will be implemented later.'],
];
