<?php
$it = require __DIR__.'/../it/reservation_settings.php';
return array_replace_recursive($it, [
 'common'=>['save'=>'Save','cancel'=>'Cancel','add'=>'Add','remove'=>'Remove','yes'=>'Yes','no'=>'No','from'=>'From','to'=>'To','actions'=>'Actions','name'=>'Name','weekdays'=>'Days of the week'],
 'index'=>['title'=>'Settings','reservations'=>'Reservations','reservations_help'=>'Operational settings saved in the tenant profile.','hours'=>'Opening hours','pax'=>'Maximum guests per time slot','sitting'=>'Maximum table stay (in minutes)','notifications'=>'Notification delivery methods','operations'=>'Operations','operations_help'=>'Departments used for staff, production and order printing.','departments'=>'Departments','rooms'=>'Rooms','automations'=>'Automations','automations_help'=>'Automatic rules related to reservations.','reminder_question'=>'How many hours before the reservation should the customer be reminded?'],
 'reminder'=>['title'=>'Reservation reminder','updated'=>'Reservation reminder hours updated successfully.'],
 'sitting'=>['title'=>'Maximum table stay','label'=>'Maximum table stay (in minutes)','updated'=>'Maximum table stay updated successfully.'],
 'notifications'=>['title'=>'Notification delivery methods','updated'=>'Notification delivery methods updated successfully.'],
 'opening'=>['title'=>'Opening hours','help'=>'Configure standard hours and special closures by date range.','slot_size'=>'Slot duration','slot_help'=>'Determines the duration of slots generated for lunch and dinner.','minutes'=>':count minutes','availability'=>'Manage availability and time ranges.','meal_open'=>':meal open','start'=>'Start of :meal','end'=>'End of :meal','special'=>'Special closures / sold out','special_help'=>'Configure date ranges when lunch or dinner cannot be booked.','lunch_closed'=>'Lunch closed','dinner_closed'=>'Dinner closed','empty'=>'No special closures configured.','save'=>'Save hours','service_error'=>'Select at least one service to close.','updated'=>'Opening hours updated successfully.'],
 'pax'=>['title'=>'Guests per time slot','help'=>'Set standard capacity and overrides by date range.','fallback'=>'Default guests','fallback_help'=>'Number of guests used when a time slot has no specific value.','apply'=>'Apply the default to all weekly slots','max'=>'Maximum guests per time slot.','closed'=>'Service closed or no slots configured.','ranges'=>'Configuration for specific date ranges','ranges_help'=>'Manage exceptions or periods with a different capacity from the weekly rule.','lunch'=>'Lunch guests','dinner'=>'Dinner guests','standard'=>'standard','empty'=>'No specific date range configured.','save'=>'Save guest capacity','value_error'=>'Enter at least one guest capacity value.','updated'=>'Guest capacity configuration updated successfully.'],
 'days'=>['lunedi'=>'Monday','martedi'=>'Tuesday','mercoledi'=>'Wednesday','giovedi'=>'Thursday','venerdi'=>'Friday','sabato'=>'Saturday','domenica'=>'Sunday'],
 'day_short'=>['lunedi'=>'Mon','martedi'=>'Tue','mercoledi'=>'Wed','giovedi'=>'Thu','venerdi'=>'Fri','sabato'=>'Sat','domenica'=>'Sun'],
 'meals'=>['pranzo'=>'Lunch','cena'=>'Dinner'],
]);
