<?php

return [
    'title' => 'Prenotazioni', 'back' => 'Indietro', 'next' => 'Avanti', 'today' => 'Oggi', 'refresh' => 'Aggiorna prenotazioni', 'search' => 'Cerca prenotazione', 'new' => 'Nuova prenotazione', 'edit' => 'Modifica prenotazione', 'detail' => 'Dettaglio prenotazione', 'detail_heading' => 'DETTAGLIO PRENOTAZIONE', 'waitlist' => 'Lista d’attesa', 'walk_in' => 'Nuovo Walk In', 'lunch' => 'Pranzo', 'dinner' => 'Cena', 'all_day' => 'Tutte del giorno', 'room' => 'Sala', 'timeslots' => 'Vedi prenotazioni per fascia oraria', 'slot' => 'Fascia', 'booked' => 'Prenotati', 'closed' => 'Ristorante chiuso in questa data.', 'arriving' => 'In arrivo', 'serving' => 'Servendo', 'customer_booking' => 'Cliente / prenotazione', 'tables_stay' => 'Tavoli / permanenza', 'empty' => 'Nessuna prenotazione per la selezione corrente.', 'close' => 'Chiudi', 'confirm' => 'Conferma', 'operation_confirm' => 'Conferma operazione', 'status_confirm' => 'Confermi il cambio di stato della prenotazione?', 'booking_notes' => 'Note prenotazione',
    'form' => ['hint' => 'Digita almeno 4 caratteri in uno dei campi cliente per cercare un cliente esistente.', 'phone' => 'Prefisso e telefono', 'prefix' => 'Prefisso', 'email' => 'Email', 'firstname' => 'Nome', 'lastname' => 'Cognome', 'date' => 'Data', 'time' => 'Orario', 'select_time' => 'Seleziona orario', 'people' => 'Numero persone', 'customer_language' => 'Lingua del cliente', 'status' => 'Stato', 'notes' => 'Note', 'send_proposal' => 'Invia una proposta di modifica al cliente', 'send_proposal_help' => 'Attivando questa opzione il salvataggio invierà la proposta al cliente invece di essere un semplice aggiornamento.', 'restaurant_note' => 'Note del ristorante', 'assign_tables' => 'Assegna tavoli', 'save' => 'Salva prenotazione', 'delete' => 'Elimina', 'delete_confirm' => 'Eliminare la prenotazione?'],
    'statuses' => ['pending' => 'Inserita', 'accepted' => 'Accettata', 'denied' => 'Rifiutata', 'canceled' => 'Cancellata', 'no-show' => 'No show', 'seated' => 'Seduti', 'waiting' => 'In attesa', 'finalized' => 'Completata'],
    'tables' => ['title' => 'Gestione tavoli assegnati', 'description' => 'Seleziona uno o più tavoli per questa prenotazione.', 'search' => 'Cerca tavolo o sala', 'selected' => 'Tavoli selezionati', 'available' => 'Tavoli disponibili', 'empty' => 'Nessun tavolo disponibile con questi criteri.', 'confirm' => 'Conferma selezione', 'none' => 'Nessun tavolo selezionato.', 'one' => 'tavolo selezionato', 'many' => 'tavoli selezionati', 'roomless' => 'Senza sala', 'select_first' => 'Seleziona prima un orario.'],
    'show' => ['status' => 'Stato', 'datetime' => 'Data e ora', 'at' => 'alle', 'people' => 'Persone', 'tables' => 'Tavoli', 'unassigned' => 'Non assegnati', 'customer' => 'Cliente', 'language' => 'Lingua', 'customer_notes' => 'Note cliente', 'origin' => 'Origine', 'created_at' => 'Inserita il', 'history' => 'Cronologia modifiche prenotazione', 'date' => 'Data', 'event' => 'Evento', 'author' => 'Autore', 'details' => 'Dettagli', 'no_history' => 'Nessuna modifica registrata.', 'events' => ['created' => 'Inserita', 'updated' => 'Modificata', 'status_changed' => 'Cambio stato', 'booking_canceled' => 'Cancellata', 'tables_changed' => 'Tavoli modificati', 'deleted' => 'Eliminata']],
    'waitlist_page' => ['title' => 'Lista d’Attesa', 'refresh' => 'Aggiorna lista', 'manage' => 'Gestione Lista d’Attesa', 'search' => 'Cerca cliente', 'search_placeholder' => 'Nome, cognome, email o telefono', 'add_customer' => 'Aggiungi cliente', 'new_customer' => 'Nuovo Cliente in Attesa', 'existing' => 'Cliente esistente selezionato', 'add' => 'Aggiungi', 'actions' => 'Azioni', 'customer' => 'Cliente', 'people' => 'Persone', 'added_at' => 'Inserita alle', 'wait' => 'Attesa', 'status' => 'Stato', 'notified' => 'Avvisato', 'waiting' => 'In attesa', 'empty' => 'Nessuno in lista d’attesa per oggi.', 'notify' => 'Avvisa cliente', 'seat' => 'Accomoda', 'remove' => 'Rimuovi'],
    'walkin_page' => ['create' => 'CREA NUOVO WALK IN', 'description' => 'Occupa lo slot senza registrare dati personali del cliente.', 'table_assignment' => 'Assegnazione tavoli', 'select_tables' => 'Seleziona tavoli', 'save' => 'Salva Walk In', 'stats' => 'Prenotazioni per fascia oraria (:date)'],
    'messages' => ['select_datetime' => 'Seleziona data e orario prima di assegnare i tavoli.', 'select_time' => 'Seleziona un orario prima di scegliere i tavoli.', 'saved' => 'Prenotazione salvata correttamente.', 'deleted' => 'Prenotazione eliminata.', 'tables_saved' => 'Tavoli assegnati correttamente.', 'walkin_saved' => 'Walk In inserito correttamente.', 'contact_required' => 'Inserisci almeno un recapito email o telefono.', 'customer_phone_taken' => 'Questo numero di telefono è già associato a un cliente. Seleziona il cliente esistente dai suggerimenti.', 'customer_email_taken' => 'Questo indirizzo email è già associato a un cliente. Seleziona il cliente esistente dai suggerimenti.', 'waitlist_added' => 'Cliente aggiunto alla lista d’attesa.', 'waitlist_seated' => 'Cliente accomodato e aggiunto alle prenotazioni di oggi.', 'waitlist_removed' => 'Cliente rimosso dalla lista d’attesa.'],
    'actions' => ['accept' => 'Accetta', 'deny' => 'Rifiuta', 'accept_confirm' => 'Accettare la prenotazione?', 'deny_confirm' => 'Rifiutare la prenotazione?'],
    'proposal_requires_changes' => 'Per inviare una proposta modifica data, orario o numero di persone.',
];
