<?php

return [
    'title'=>'Clienti','home'=>'Home','back'=>'Indietro','save'=>'Salva','cancel'=>'Annulla','yes'=>'SÌ','no'=>'NO','language'=>'Lingua','info'=>'Info',
    'actions'=>['create'=>'Crea cliente','import'=>'Importa clienti da CSV','refresh'=>'Aggiorna','view'=>'Vedi','edit'=>'Modifica','delete'=>'Elimina'],
    'index'=>['search'=>'Cerca cliente','advanced_filters'=>'Filtri avanzati','reset_filters'=>'Reset filtri','send_marketing'=>'Invia a Marketing','customer'=>'Cliente','last_visit'=>'Ultima visita','area'=>'Zona','empty'=>'Nessun cliente trovato.'],
    'filters'=>['all_f'=>'-- Tutte --','all_m'=>'-- Tutti --','none'=>'-- Nessun filtro --','province'=>'Provincia','municipality'=>'Comune','booking_status'=>'Stato prenotazione','no_show'=>'No Show >=','example'=>'Es. 1, 2, 3...','visit_from'=>'Ultima visita (da)','visit_to'=>'Ultima visita (a)','not_visited_since'=>'Non vengono da','visited_within'=>'Sono venuti entro','birth_month'=>'Mese compleanno','birth_day'=>'Giorno compleanno','month'=>':count mese|:count mesi','over_year'=>'Oltre 1 anno'],
    'months'=>['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
    'statuses'=>['pending'=>'Inserita','accepted'=>'Accettata','denied'=>'Rifiutata','canceled'=>'Cancellata','no-show'=>'No show','seated'=>'Seduti','waiting'=>'In attesa','finalized'=>'Completata','deleted'=>'Eliminata'],
    'form'=>['create'=>'CREA CLIENTE','edit'=>'MODIFICA CLIENTE','firstname'=>'Nome','lastname'=>'Cognome','email'=>'Email','phone'=>'Telefono','telegram'=>'Telegram ID','birthdate'=>'Data di nascita','region'=>'Regione','province'=>'Provincia','municipality'=>'Comune','select_region'=>'-- Seleziona Regione --','select_province'=>'-- Seleziona Provincia --','select_municipality'=>'-- Seleziona Comune --','notes'=>'Note interne (non leggibili dal cliente)','notes_placeholder'=>'Inserisci qui le tue annotazioni su questo cliente.','marketing'=>'Autorizzazione marketing','blacklisted'=>'In blacklist'],
    'show'=>['card'=>'SCHEDA :name','create_booking'=>'Crea prenotazione','source'=>'Sorgente'],
    'delete'=>['title'=>'ELIMINA CLIENTE','confirm'=>'Sei sicuro di voler eliminare :name?','button'=>'Sì, elimina'],
    'import'=>['title'=>'IMPORTA CLIENTI DA CSV','file'=>'File CSV','sync'=>'Sincronizza','loading'=>'Caricamento...','documentation'=>'DOCUMENTAZIONE','heading'=>'Importazione clienti tramite CSV','intro'=>'Questa schermata prepara il caricamento massivo dei clienti. La funzionalità di importazione verrà implementata successivamente.','recommended'=>'Campi consigliati','field'=>'Campo','description'=>'Descrizione','example'=>'Esempio','firstname'=>'Nome del cliente.','lastname'=>'Cognome del cliente.','phone'=>'Telefono in formato internazionale quando possibile.','email'=>'Indirizzo email del cliente.','birthdate'=>'Data di nascita in formato ISO.'],
    'history'=>['title'=>'Storico prenotazioni cliente (:count)','finalized'=>'Consumate','canceled'=>'Cancellate/eliminate','denied'=>'Rifiutate','no_show'=>'No show','date'=>'Data','time'=>'Orario','pax'=>'Pax','status'=>'Stato','notes'=>'Note','empty'=>'Nessuna prenotazione per questo cliente.'],
    'messages'=>['created'=>'Cliente creato con successo.','updated'=>'Cliente aggiornato con successo.','deleted'=>'Cliente eliminato con successo.','marketing_pending'=>'La funzionalità marketing sarà implementata successivamente.','import_pending'=>'Import clienti da CSV pronto: la sincronizzazione sarà implementata successivamente.'],
];
