<?php
return [
 'common'=>['save'=>'Salva','cancel'=>'Annulla','add'=>'Aggiungi','remove'=>'Rimuovi','yes'=>'Sì','no'=>'No','from'=>'Dal','to'=>'Al','actions'=>'Azioni','name'=>'Nome','weekdays'=>'Giorni della settimana'],
 'index'=>['title'=>'Impostazioni','reservations'=>'Prenotazioni','reservations_help'=>'Configurazioni operative salvate sul profilo tenant.','hours'=>'Orari','pax'=>'Pax massimi per slot orario','sitting'=>'Tempo massimo permanenza al tavolo (in minuti)','notifications'=>'Modalità di invio notifiche','operations'=>'Operatività','operations_help'=>'Reparti usati per personale, produzione e invio comande.','departments'=>'Reparti','rooms'=>'Sale','automations'=>'Automazioni','automations_help'=>'Regole automatiche collegate alle prenotazioni.','reminder_question'=>'Quante ore prima ricordare al cliente della prenotazione?'],
 'reminder'=>['title'=>'Promemoria prenotazione','updated'=>'Ore promemoria prenotazione aggiornate correttamente.'],
 'sitting'=>['title'=>'Tempo massimo permanenza al tavolo','label'=>'Tempo massimo permanenza al tavolo (in minuti)','updated'=>'Tempo massimo permanenza aggiornato correttamente.'],
 'notifications'=>['title'=>'Modalità di invio notifiche','updated'=>'Modalità di invio notifiche aggiornata correttamente.'],
 'opening'=>['title'=>'Orari di apertura','help'=>'Configura orari standard e chiusure speciali per intervallo.','slot_size'=>'Durata degli slot','slot_help'=>'Determina la durata degli slot generati per pranzo e cena.','minutes'=>':count minuti','availability'=>'Gestisci disponibilità e fasce orarie.','meal_open'=>':meal aperto','start'=>'Inizio :meal','end'=>'Fine :meal','special'=>'Chiusure speciali / tutto esaurito','special_help'=>'Configura intervalli di date in cui pranzo o cena non devono essere prenotabili.','lunch_closed'=>'Pranzo chiuso','dinner_closed'=>'Cena chiusa','empty'=>'Nessuna chiusura speciale configurata.','save'=>'Salva orari','service_error'=>'Seleziona almeno un servizio da chiudere.','updated'=>'Orari aggiornati correttamente.'],
 'pax'=>['title'=>'Pax per slot orario','help'=>'Imposta capienza standard ed eccezioni per intervallo di date.','fallback'=>'Pax predefiniti','fallback_help'=>'Numero di pax usato quando una singola fascia oraria non ha un valore specifico.','apply'=>'Applica il valore predefinito a tutti gli slot settimanali','max'=>'Massimo pax per fascia oraria.','closed'=>'Servizio chiuso o senza slot configurati.','ranges'=>'Configurazione per intervalli specifici','ranges_help'=>'Gestisci eccezioni o periodi con capienza diversa rispetto alla regola settimanale.','lunch'=>'Pax pranzo','dinner'=>'Pax cena','standard'=>'standard','empty'=>'Nessun intervallo specifico configurato.','save'=>'Salva configurazione pax','value_error'=>'Inserisci almeno un valore pax.','updated'=>'Configurazione pax aggiornata correttamente.'],
 'days'=>['lunedi'=>'Lunedì','martedi'=>'Martedì','mercoledi'=>'Mercoledì','giovedi'=>'Giovedì','venerdi'=>'Venerdì','sabato'=>'Sabato','domenica'=>'Domenica'],
 'day_short'=>['lunedi'=>'Lun','martedi'=>'Mar','mercoledi'=>'Mer','giovedi'=>'Gio','venerdi'=>'Ven','sabato'=>'Sab','domenica'=>'Dom'],
 'meals'=>['pranzo'=>'Pranzo','cena'=>'Cena'],
];
