@php($firstLanguage = array_key_first($languages) ?? 'it')
<div class="content"><div class="main-content"><h5 class="page-title mb-6">{{ __('marketing_forms.create') }}</h5><form wire:submit="save" x-data="{ activeLanguage: '{{ $firstLanguage }}' }" class="box"><div class="box-body space-y-5">
<div><label>Tipo</label><select wire:model.live="type" class="form-control">@foreach($types as $key=>$definition)<option value="{{ $key }}">{{ $definition['name'] }}</option>@endforeach</select></div>
<label class="flex gap-2"><input type="checkbox" wire:model.live="multilingual" @change="if (!$event.target.checked) activeLanguage = '{{ $firstLanguage }}'" class="ti-switch"> Abilita tutte le lingue del tenant</label>
<div class="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0"><nav role="tablist" aria-label="Lingue" class="--prevent-on-load-init flex min-w-max gap-2 rounded-xl border border-defaultborder bg-defaultbackground p-1">@foreach($languages as $code=>$meta) @if($loop->first || $multilingual)<button type="button" role="tab" :aria-selected="activeLanguage === '{{ $code }}'" @click="activeLanguage = '{{ $code }}'" class="ti-btn !mb-0 inline-flex items-center justify-center gap-2 rounded-lg !px-4 !py-2 text-sm font-semibold transition" :class="activeLanguage === '{{ $code }}' ? 'ti-btn-primary-full shadow-sm' : 'ti-btn-light text-defaulttextcolor'"><span>{{ $meta['flag'] }}</span><span>{{ $meta['label'] }}</span></button>@endif @endforeach</nav></div>
@foreach($languages as $code=>$meta) @if($loop->first || $multilingual)<section x-cloak x-show="activeLanguage === '{{ $code }}'" x-transition.opacity role="tabpanel" class="rounded border border-defaultborder bg-defaultbackground p-4"><label for="title-{{ $code }}">Titolo {{ $meta['label'] }}</label><input id="title-{{ $code }}" wire:model="translations.{{ $code }}.title" class="form-control"><label for="description-{{ $code }}">Descrizione {{ $meta['label'] }}</label><textarea id="description-{{ $code }}" wire:model="translations.{{ $code }}.description" class="form-control"></textarea>@error('translations.'.$code.'.title')<p class="text-danger">{{ $message }}</p>@enderror</section>@endif @endforeach
@if($type==='event')<div><label>Calendario evento</label><select wire:model="event_mode" class="form-control"><option value="single">Singolo giorno</option><option value="dates">Più giorni</option><option value="range">Intervallo di date</option></select></div>@endif
@if($type==='generic')<div><label>Personale da notificare</label>@foreach($users as $user)<label class="block"><input type="checkbox" wire:model="notify_user_ids" value="{{ $user->id }}"> {{ $user->name }} ({{ $user->email }})</label>@endforeach</div>@endif
<label class="block"><input type="checkbox" wire:model="is_active"> Attivo</label>@if($type!=='generic')<label class="block"><input type="checkbox" wire:model="accepts_coupons"> Accetta coupon</label>@endif
</div><div class="box-footer"><button class="ti-btn ti-btn-success" type="submit">Crea e configura campi</button> <a href="{{ route('marketing.forms.index') }}" class="ti-btn ti-btn-light">Annulla</a></div></form></div></div>
