<div class="content"><div class="main-content"><h5 class="page-title mb-6">{{ __('marketing_forms.create') }}</h5><form wire:submit="save" class="box"><div class="box-body space-y-5">
<div><label>Tipo</label><select wire:model.live="type" class="form-control">@foreach($types as $key=>$definition)<option value="{{ $key }}">{{ $definition['name'] }}</option>@endforeach</select></div>
<label class="flex gap-2"><input type="checkbox" wire:model.live="multilingual" class="ti-switch"> Abilita tutte le lingue del tenant</label>
<div class="border-b"><nav class="flex gap-4">@foreach($languages as $code=>$meta) @if($loop->first || $multilingual)<span class="p-3">{{ $meta['flag'] }} {{ $meta['label'] }}</span>@endif @endforeach</nav></div>
@foreach($languages as $code=>$meta) @if($loop->first || $multilingual)<div class="bg-gray-100 p-4"><label>Titolo {{ $meta['label'] }}</label><input wire:model="translations.{{ $code }}.title" class="form-control"><label>Descrizione {{ $meta['label'] }}</label><textarea wire:model="translations.{{ $code }}.description" class="form-control"></textarea>@error('translations.'.$code.'.title')<p class="text-danger">{{ $message }}</p>@enderror</div>@endif @endforeach
@if($type==='event')<div><label>Calendario evento</label><select wire:model="event_mode" class="form-control"><option value="single">Singolo giorno</option><option value="dates">Più giorni</option><option value="range">Intervallo di date</option></select></div>@endif
@if($type==='generic')<div><label>Personale da notificare</label>@foreach($users as $user)<label class="block"><input type="checkbox" wire:model="notify_user_ids" value="{{ $user->id }}"> {{ $user->name }} ({{ $user->email }})</label>@endforeach</div>@endif
<label class="block"><input type="checkbox" wire:model="is_active"> Attivo</label>@if($type!=='generic')<label class="block"><input type="checkbox" wire:model="accepts_coupons"> Accetta coupon</label>@endif
</div><div class="box-footer"><button class="ti-btn ti-btn-success" type="submit">Crea e configura campi</button> <a href="{{ route('marketing.forms.index') }}" class="ti-btn ti-btn-light">Annulla</a></div></form></div></div>
